services:
  python:
    build: ./docker/python
    volumes:
      - ./src:/root/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
  db:
    build: ./docker/db
    ports: 
      - "5432:5432"
    volumes:
      - ./docker/db/db-data:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres